table Country
	lineageTag: 4b5b7a7f-a5f5-4baf-b721-09d0bfa8d424

	measure 'Total country' = DISTINCTCOUNT(Country[Country])
		formatString: 0
		lineageTag: 2d47ac23-6633-434e-870c-624ae0c6e562

	measure 'Total City' = DISTINCTCOUNT(Sheet1[City])
		formatString: 0
		lineageTag: 6917bd90-fe57-4107-9325-6dd4908cd00e

		changedProperty = IsHidden

	measure 'Total cuisines' = DISTINCTCOUNT(Sheet1[Cuisines])
		formatString: 0
		lineageTag: 73de8f2c-d356-4f41-8b90-fafaed612779

	measure 'Average Ratings' = ```
			AVERAGE(Sheet1[Rating]) 
			```
		lineageTag: c59e619d-c601-44c4-9485-9e9d8e704345

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Country Code'
		dataType: int64
		formatString: 0
		lineageTag: 97540d38-7b8c-48cf-a24b-03d1ee93bfe2
		summarizeBy: none
		sourceColumn: Country Code

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 3ccef857-cfc5-4936-8c7e-386e19c0a088
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	partition Country = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("E:\DA classes\Project\Power Bi\Country-Code.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country Code", Int64.Type}, {"Country", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

