table Country
	lineageTag: 4b5b7a7f-a5f5-4baf-b721-09d0bfa8d424

	column 'Country Code'
		dataType: int64
		formatString: 0
		lineageTag: 97540d38-7b8c-48cf-a24b-03d1ee93bfe2
		summarizeBy: none
		sourceColumn: Country Code

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 3ccef857-cfc5-4936-8c7e-386e19c0a088
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	partition Country = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("E:\DA classes\Project\Power Bi\Country-Code.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country Code", Int64.Type}, {"Country", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

